#
# This config file is meant for settings that affect your whole TIM page.
# You can access these values throughout all documents by using the `site` variable.
# For example, you can use `{{ site.title }}` to access the title of your page.

# The title of your page
title: My TIM page
# Specify the base path of your page. This is the path that is used to generate URLs.
base_path: path/to/your/tim/page

course_chapters:
    1:
        title: Start here
        points: false
        sections:
            - title: Test section
              path: part1
              icon: info
              points: false
